name: Build project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :plotsquared-bukkit:shadowJar

      - name: Find all jar files
        run: find . -name "*.jar"

      - name: List core jars
        run: ls -la Core/build/libs

      - name: List bukkit jars
        run: ls -la Bukkit/build/libs

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            Core/build/libs/*.jar
            Bukkit/build/libs/*.jar
